
ALTER TABLE t_p18264164_domain_sales_website.users
  ADD COLUMN IF NOT EXISTS last_name VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS middle_name VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS phone VARCHAR(50) DEFAULT '';

ALTER TABLE t_p18264164_domain_sales_website.orders
  ADD COLUMN IF NOT EXISTS domain_status VARCHAR(50) DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS verified_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS connected_api VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS connected_ip VARCHAR(100) DEFAULT '',
  ADD COLUMN IF NOT EXISTS connection_status VARCHAR(50) DEFAULT 'none';
